### ISSUE TITLE
Binary missing in release

### ISSUE THREAD

**Issue by ryanabo** [edawson/rkmh#5]
Hi, 

I am stuck with gcc 4.8.5, so I cannot compile but the binary file in the release is also not present. Any chance you could update?

Thanks,
Ryan

**Comment by edawson** [comment]
Hey Ryan,

I had some initial problems getting the binary release out; I can try to redistribute them. Are you on Linux or Mac?

Cheers,
   Eric

**Comment by edawson** [comment]
Hey Ryan,

The new release has a Mac OS binary attached. I'll get an Ubuntu binary up tonight.

Best,
   Eric

**Comment by edawson** [comment]
Going to close, but happy to send an updated binary if one is still desired.
